# Generated by Django 4.0.3 on 2022-12-07 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_serviceappointment_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvinsvo',
            name='import_href',
            field=models.CharField(default='/api/automobiles/1C3CC5FB2AN120174/', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='service_rest.technician'),
        ),
    ]
