# Generated by Django 4.0.3 on 2022-12-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_inventoryvinsvo_import_href_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
