# Generated by Django 4.0.3 on 2022-12-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_serviceappointment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='complete',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
