# Generated by Django 4.0.3 on 2022-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_serviceappointment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvinsvo',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryvinsvo',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryvinsvo',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
