# Generated by Django 4.0.3 on 2022-12-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_inventoryvinsvo_manufacturer_inventoryvinsvo_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
