# Generated by Django 4.0.3 on 2022-12-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_serviceappointment_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='year',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='service_rest.inventoryvinsvo'),
        ),
    ]
