# Generated by Django 4.0.3 on 2022-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_serviceappointment_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='import_href',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='vin_vo',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
