# Generated by Django 4.0.3 on 2022-12-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_alter_inventoryvinsvo_import_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='import_href',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='manufacturer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='model',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='vin_vo',
            field=models.CharField(default=None, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryvinsvo',
            name='year',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
